---
apiVersion: v2
name: <xyz>
description: A Helm chart to deploy the <xyz> service
type: application
version: 0.1.0

dependencies:
  - name: polaris-namespace
    version: 1.7.1
    repository: http://polaris-charts.infra
    alias: namespace
  - name: polaris-secret
    version: 1.4.0
    repository: http://polaris-charts.infra
    condition: polaris-secret.enabled
